### ISSUE TITLE
unmaintained crate warning from cargo audit

### ISSUE THREAD

**Issue by edwardoranj** [omnia-network/ic-websocket-cdk-rs#11]
```
Crate:     serde_cbor
Version:   0.11.2
Warning:   unmaintained
Title:     serde_cbor is unmaintained
Date:      2021-08-15
ID:        RUSTSEC-2021-0127
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0127
Dependency tree:
serde_cbor 0.11.2
└── ic-websocket-cdk 0.4.
```

**Comment by ilbertt** [comment]
Yeah, that's an unfortunate choice that I made when working on the first IC WebSocket implementation.
I figured it out too late while already in production, but I've been reluctant to switch to crates like [ciborium](https://crates.io/crates/ciborium) for two reasons:

1. even if the crate is unmaintained, the old maintainer [says](https://github.com/pyfisch/cbor#project-is-archived) that "if the crate works for you there is no need to switch to another implementation"
2. while testing the usage of ciborium for the IC WebSocket Rust CDK, I was encountering errors with the messages' deserialization on the gateway (see ciborium's [Compatibility with Other Implementations](https://github.com/enarx/ciborium#compatibility-with-other-implementations) too). This means that switching to a new CBOR library must be done on both the gateway and the CDK at the same time, but this can break canisters that don't upgrade to the new CDK

I should definitely take the time to test new CBOR libraries better and eventually upgrade to one of them at some point, and I would be really happy if anyone would like to help me in that!

**Comment by edwardoranj** [comment]
> Yeah, that's an unfortunate choice that I made when working on the first IC WebSocket implementation. I figured it out too late while already in production, but I've been reluctant to switch to crates like [ciborium](https://crates.io/crates/ciborium) for two reasons:
> 
> 1. even if the crate is unmaintained, the old maintainer [says](https://github.com/pyfisch/cbor#project-is-archived) that "if the crate works for you there is no need to switch to another implementation"
> 2. while testing the usage of ciborium for the IC WebSocket Rust CDK, I was encountering errors with the messages' deserialization on the gateway (see ciborium's [Compatibility with Other Implementations](https://github.com/enarx/ciborium#compatibility-with-other-implementations) too). This means that switching to a new CBOR library must be done on both the gateway and the CDK at the same time, but this can break canisters that don't upgrade to the new CDK
> 
> I should definitely take the time to test new CBOR libraries better and eventually upgrade to one of them at some point, and I would be really happy if anyone would like to help me in that!

Thanks for your reply, just wanted to confirm if the `serde_cbor` crate usage was intended.
